ci:
  autoupdate: weekly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [ '--all', '--', '--verbose' ]
      - id: cargo-check
        args: [ '--verbose', '--all-features', '--workspace' ]
      - id: clippy
        args: [ '--verbose', '--all-features', '--all-targets', '--fix',
                '--allow-dirty', '--allow-staged' ]
