ci:
  autoupdate: weekly
repos:
  - repo: github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
        args: [ '--verbose', '--all']
      - id: cargo-check
        args: [ '--verbose', '--all-features', '--workspace' ]
      - id: cargo-clippy
        args: [ '--verbose', '--fix' ]