ci:
  autoupdate: weekly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/kucera-lukas/rusty-battery
    rev: 148b5f3a95e77c1dba74d30d7bcd2fce57e0ef53
    hooks:
      - id: cargo-fmt
      - id: cargo-check
      - id: clippy
