[package]
name = "rusty-battery"
version = "0.1.0"
description = "CLI tool to help you care about your device's battery health."
repository = "https://github.com/kucera-lukas/rusty-battery"
readme = "README.md"
license = "MIT"
keywords = ['cli', "battery-life", "desktop-notifications"]
categories = ['command-line-utilities']
edition = "2018"

[dependencies]
structopt = "0.3"
thiserror = "1.0.29"
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.14"
battery = "0.7.8"
notify-rust = "4"
