name: Clippy Check

on:
  pull_request:

jobs:
  clippy:
    name: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.3.4

      - name: Install stable with clippy
        uses: dtolnay/rust-toolchain@clippy

      - name: Check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
