name: Code Style

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  lint:
    name: ${{ matrix.os }} / ${{ matrix.toolchain }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        toolchain: [ stable ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.3.4

      - name: Install ${{ matrix.toolchain }} with clippy and rustfmt
        uses: dtolnay/rust-toolchain@${{ matrix.toolchain }}
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Run cargo check
        run: cargo chek --verbose --all-features --workspace

      - name: Run cargo fmt
        run: cargo fmt --all -- --check --verbose

      - name: Run cargo clippy
        run: cargo clippy --verbose --all-features --all-targets -- -D warnings
