name: Release

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  TARGET: x86_64-unknown-linux-gnu

jobs:
  release:
    name: ${{ matrix.os }} / ${{ matrix.toolchain }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [nightly]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Release Please
        uses: GoogleCloudPlatform/release-please-action@v3.5
        id: release-please
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          release-type: rust

      # upload artifact if release was created
      - name: Git Checkout
        if: ${{ steps.release-please.outputs.release-created }}
        uses: actions/checkout@v3.5.3

      - name: Install minimal ${{ matrix.toolchain }}
        if: ${{ steps.release-please.outputs.release-created }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          target: ${{ env.TARGET }}

      - name: Create Bin Directory
        if: ${{ steps.release-please.outputs.release-created }}
        run: mkdir bin --verbose

      - name: Release Build
        if: ${{ steps.release-please.outputs.release-created }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ env.TARGET }} -Z unstable-options --out-dir bin

      - name: Archive Binary
        if: ${{ steps.release-please.outputs.release-created }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: rusty-battery-${{ env.TARGET }}
          path: bin/rusty-battery
